version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app_network
    volumes:
      - ./frontend:/frontend

  production:
    image: nginx:stable
    container_name: production
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
